### ISSUE TITLE
read, write와 recv, send 함수의 차이점

### ISSUE THREAD

**Issue by l-yohai** [get-Pork-Belly/Webserv#18]
- read, write 함수와 recv, send 함수의 차이점을 알아본다.
- recv, send 함수를 어떤 부분에 어떻게 사용할 수 있을지 학습한다.

**Comment by l-yohai** [comment]
[참고 1 입출력함수](https://valueelectronic.tistory.com/224)
[참고 2 네트워크프로그래밍](https://dgkim5360.tistory.com/entry/beej-guide-to-network-programming-translation-part-1)

```C
#include <sys/types.h>
#include <sys/socket.h>

ssize_t send(int sockfd, const void *buf, int len, int flags);
// sockfd: 목적지의 socket file descriptor. socket()이나 accept()의 리턴값이 사용된다.
// buf: 보내고자 하는 데이터를 가리키는 pointer
// len: 보내고자 하는 데이터의 byte 길이
// return value: 실제 보내진 데이터의 byte 길이.
// return 값이 len 보다 작을 수 있음 - 이 때의 처리가 필요함 (모든 패킷이 전송되지 않았다는 것이다.) 무조건 buf의 길이와 len의 길이가 같아질 때까지 반복문을 돌던가 해야할듯.

ssize_t recv(int sockfd, void *buf, int len, int flags);
// len: 버퍼의 최대 byte길이
// return value: 받은 데이터를 읽어 buffer에 넣은 byte 길이 반환.
//(오류: -1 리턴, errno에 오류값을 넣어줌. 0이 반환되면 상대방이 연결을 끊었다는 의미임.)
```

* sendto()와 recvfrom()은 Dgram(Data gram-style)으로, 원격 host와 연결되어 있지 않은 상황에서 사용된다.
* 위 두 함수는 UDP 통신에서 주로 사용되는 듯 하다. connect()가 되지 않았을 때 사용하는듯..? 허용함수에 없는 내용이니 넘어가자.

#### MSG_PEEK 옵션 (recv 함수에만 존재)
- 입력 버퍼에 수신된 데이터의 존재 유무를 확인한다.
- 큐에서 데이터를 제거하지 않고 받는 큐의 시작에서부터 데이터를 반환받기 위해 사용함.
- 이 옵션을 사용하지 않으면 recv 함수 호출 이후 바로 버퍼에서 데이터가 사라지지만, 이 옵션을 사용하면 버퍼에 읽어들인 값이 보존됨.
    - 근데 0(EOF)가 리턴될 때 까지 로컬 버퍼에 수신버퍼의 값을 strjoin 해주면 되는 거 아닌가..? 왜 MSG_PEEK으로 수신버퍼 메모리를 할당하지 않고 미리 메세지를 확인해야 하는건지 모르겠다.

#### recv와 send, read와 write
* recv와 send, read와 write는 대체로 비슷하지만 recv/send에서는 플래그 등 다른 옵션을 사용할 수 있기 때문에 더욱 전문적이고 강력하다는 장점이 있다.
* 하지만 recv와 send는 소켓에서만 작동한다. 예를들어 USB 포트 등 다른 입출력장치에 사용하기 위해서는 read/write를 사용해야 한다.

**Comment by l-yohai** [comment]
## 테스트

peek_send.c

```C
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <arpa/inet.h>
void error_handling(char *message);

#define TEST "Hello Im fine thankyou and you how are you my name is haha"

int main(int argc, char *argv[])
{
	int sock;
	struct sockaddr_in send_adr;
	if(argc!=3) {
		printf("Usage : %s <IP> <port>\n", argv[0]);
		exit(1);
	 }

	sock=socket(PF_INET, SOCK_STREAM, 0);
	memset(&send_adr, 0, sizeof(send_adr));
	send_adr.sin_family=AF_INET;
	send_adr.sin_addr.s_addr=inet_addr(argv[1]);
	send_adr.sin_port=htons(atoi(argv[2]));
  	
	if(connect(sock, (struct sockaddr*)&send_adr, sizeof(send_adr))==-1)
		error_handling("connect() error!");
	
	write(sock, TEST, strlen(TEST));
	close(sock);
	return 0;
}

void error_handling(char *message)
{
	fputs(message, stderr);
	fputc('\n', stderr);
	exit(1);
}
```
<br>
<br>

peek_recv.c

```C
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <arpa/inet.h>

#define BUF_SIZE 30
void error_handling(char *message);

int main(int argc, char *argv[])
{
	int acpt_sock, recv_sock;
	struct sockaddr_in acpt_adr, recv_adr;
	int str_len, state;
	socklen_t recv_adr_sz;
	char buf[BUF_SIZE];
	if(argc!=2) {
		printf("Usage : %s <port>\n", argv[0]);
		exit(1);
	}
	
	acpt_sock=socket(PF_INET, SOCK_STREAM, 0);
	memset(&acpt_adr, 0, sizeof(acpt_adr));
	acpt_adr.sin_family=AF_INET;
	acpt_adr.sin_addr.s_addr=htonl(INADDR_ANY);
	acpt_adr.sin_port=htons(atoi(argv[1]));
	
  	if(bind(acpt_sock, (struct sockaddr*)&acpt_adr, sizeof(acpt_adr))==-1)
		error_handling("bind() error");
	listen(acpt_sock, 5);
	
	recv_adr_sz=sizeof(recv_adr);
	recv_sock=accept(acpt_sock, (struct sockaddr*)&recv_adr, &recv_adr_sz);
	
	while(1)
	{
		str_len=recv(recv_sock, buf, sizeof(buf)-1, MSG_PEEK); //MSG_PEEK와 MSG_DONTWAIT를 옵션으로 넣음.        
		printf("Buf: %s, len: %d\n", buf, str_len);
		if(str_len <= 0) //MSG_PEEK : 입력 버퍼에 데이터 유무 확인하고 입력버퍼의 데이터를 지우지 않고 유지함. , MSG_DONTWAIT : 데이터가 없어도 블로킹 상태에 놓이지 않게 함.
			break;
	}

	buf[str_len]=0;
	printf("Buffering %d bytes: %s \n", str_len, buf);
 	
	str_len=recv(recv_sock, buf, sizeof(buf)-1, 0); //데이터를 읽은 뒤 입력버퍼의 데이터를 지운다.
	buf[str_len]=0;
	printf("Read again: %s \n", buf);
	close(acpt_sock);
	close(recv_sock);
	return 0; 
}

void error_handling(char *message)
{
	fputs(message, stderr);
	fputc('\n', stderr);
	exit(1);
}

```

![image](https://user-images.githubusercontent.com/49181231/95642282-87132e80-0ae2-11eb-8f54-a53451837a6f.png)

![image](https://user-images.githubusercontent.com/49181231/95642300-98f4d180-0ae2-11eb-8656-e81b384022f4.png)
### MSG_PEEK 옵션이 없을 때
![image](https://user-images.githubusercontent.com/49181231/95642310-b5910980-0ae2-11eb-9674-719dbb9d2737.png)

<br>
<br>

![image](https://user-images.githubusercontent.com/49181231/95642303-a7db8400-0ae2-11eb-84be-a5a615facf68.png)
### MSG_PEEK 옵션이 있을 때
![image](https://user-images.githubusercontent.com/49181231/95642323-c17ccb80-0ae2-11eb-8ae0-3fcde61193fc.png)

- 무한루프 걸림
- 계속 처음 읽었던 문장만 읽음.

**Comment by simian114** [comment]
recv 와 send 에 대한 정리 감사합니다! 

>이 옵션을 사용하지 않으면 recv 함수 호출 이후 바로 버퍼에서 데이터가 사라지지만, 이 옵션을 사용하면 버퍼에 읽어들인 값이 보존됨.
근데 0(EOF)가 리턴될 때 까지 로컬 버퍼에 수신버퍼의 값을 strjoin 해주면 되는 거 아닌가..? 왜 MSG_PEEK으로 수신버퍼 메모리를 할당하지 않고 미리 메세지를 확인해야 하는건지 모르겠다.

이 부분에 대해서는 아직 공부가 더 필요한것 같네여.. 저도 계속 알아보겠습니다!

**Comment by l-yohai** [comment]
> recv 와 send 에 대한 정리 감사합니다! 
> 
> >이 옵션을 사용하지 않으면 recv 함수 호출 이후 바로 버퍼에서 데이터가 사라지지만, 이 옵션을 사용하면 버퍼에 읽어들인 값이 보존됨.
> 근데 0(EOF)가 리턴될 때 까지 로컬 버퍼에 수신버퍼의 값을 strjoin 해주면 되는 거 아닌가..? 왜 MSG_PEEK으로 수신버퍼 메모리를 할당하지 않고 미리 메세지를 확인해야 하는건지 모르겠다.
> 
> 이 부분에 대해서는 아직 공부가 더 필요한것 같네여.. 저도 계속 알아보겠습니다! 
> 

답변감사합니다. man recv 에 조금 설명이 나와있긴 한데 자세하진 않네요. eunhkim 님이 말씀해주셨던 것들(errno를 쓰지 못하는 것과 미리 데이터를 확인하는것 등)은 직접 저희가 여러 테스트를 해보면서 경험적으로 파악해야 하는 부분들일 것도 같습니다.

**Comment by humblEgo** [comment]
깔끔한 정리 감사합니다. 덕분에 쉽게 개념잡을 수 있었어요! 굿굿입니다!
'write/read, send/recv가 어떻게 다른지 알겠다. 그럼 구현시에 어떤 함수를 선택해야하는가?' 라는 의문이 들었는데요. 
어떤 상황에 write/read를 사용하고, 어떤 상황에 send/recv를 써야할지는 결국 MSG_PEEK 등 '플래그의 필요여부'에 달린 것 같습니다. 그리고 이건 경험적으로 시행착오를 겪어봐야할 것 같습니다.

참고) 성능상 차이가 있는지 확인해봤는데, [이 블로그](https://m.blog.naver.com/PostView.nhn?blogId=credenda&logNo=80177079016&proxyReferer=https:%2F%2Fwww.google.com%2F)를 보면 소켓을 다룰 때엔 send/recv가 미세하게 더 효율적이지만, 이는 무시해도 좋을 정도로 미미하다고 합니다.

**Comment by l-yohai** [comment]
> 깔끔한 정리 감사합니다. 덕분에 쉽게 개념잡을 수 있었어요! 굿굿입니다!
> 'write/read, send/recv가 어떻게 다른지 알겠다. 그럼 구현시에 어떤 함수를 선택해야하는가?' 라는 의문이 들었는데요. 
> 어떤 상황에 write/read를 사용하고, 어떤 상황에 send/recv를 써야할지는 결국 MSG_PEEK 등 '플래그의 필요여부'에 달린 것 같습니다. 그리고 이건 경험적으로 시행착오를 겪어봐야할 것 같습니다.
> 
> 참고) 성능상 차이가 있는지 확인해봤는데, [이 블로그](https://m.blog.naver.com/PostView.nhn?blogId=credenda&logNo=80177079016&proxyReferer=https:%2F%2Fwww.google.com%2F)를 보면 소켓을 다룰 때엔 send/recv가 미세하게 더 효율적이지만, 이는 무시해도 좋을 정도로 미미하다고 합니다.

답변감사합니다! 말씀하신대로 여러 테스트케이스를 해보면서 경험적으로 파악해나가야 할 것 같습니다. 성능차이도 미미하면 MSG_PEEK 의 여부가 관건이겠네요 ㅠㅠ

**Comment by l-yohai** [comment]
[I/O모델](https://ozt88.tistory.com/m/20)

non blocking 이 아닌 경우 recv의 버퍼 내용이 비어있을 때 Blocking 상태에 빠지게 된다.
- 이를 해결하기 위해 MSG_PEEK 옵션으로 수신 내용이 있을지 없을지 미리 확인하여 Blocking 상태에 빠지지 않게 할 수 있음.
- 이 때 errno를 이용하여 Blocking 상태에 빠지는 것인지 미리 확인할 수 있음(EWOULDBLOCK)

그러나 우리의 경우 모든 FD를 Non Blocking으로 처리하기로 결정.

-> 따라서 MSG_PEEK 옵션을 활용하여 recv 함수를 사용할 필요는 굳이 따지자면 없음.

하지만, 효율성...을 위해 read 전에 recv(,,MSG_PEEK) 을 이용하여 수신버퍼의 내용이 존재하는지 유무를 미리 확인할 수 있다.
