### ISSUE TITLE
Response 클래스 설계

### ISSUE THREAD

**Issue by humblEgo** [get-Pork-Belly/Webserv#42]
- [x] http response 규칙 파악
  - [x] response 메소드/상태코드 별 헤더 정리
- [x] response 생성 흐름도 작성
  - [x] CGI 고려한 설계
- [x] response 클래스 멤버변수/함수 설계
- [x] Response Method

**Comment by humblEgo** [comment]
https://jongmin92.github.io/2019/02/10/Programming/object_oriented_facts_and_misunderstandings/

Server에 저장된 cgi_path로부터 body를 만들어내는 함수를 Server클래스에 포함시킬지 Response 클래스에 저장할지 결정하는 것이 고민되었는데, 위 링크를 보고 해결되었습니다.
현실세계와 달리 ‘객체는 자신의 상태를 책임지도록’ 하고, 다른 객체가 그 객체의 상태를 변화시키면 안되므로, Response 객체에 관련 함수를 포함시킵니다~

별개로 MIME_types_table과 status_code_table를 Server 클래스의 멤버변수로 추가하려합니다. 혹시 이견있으시면 말씀주세요~

**Comment by humblEgo** [comment]
> All general-purpose servers MUST support the methods GET and HEAD. All other methods are OPTIONAL.  --RFC7231

`GET`과 `HEAD`는 필수로 구현해야합니다.
우선 위 두 메서드를 구현해보고, 아래 목록의 나머지 메서드도 학습을 위해 구현하는 것을 고려해봅시다.

| Method       | Description                                                          | Sec.       |
|------------|----------------------------------------------|---------|
| GET             | 대상 리소스의 현재 표현 전송                                 | 4.3.1    |
| HEAD          | GET과 동일하나, status-line과 header부문만 전송| 4.3.2    |
| POST           | 요청 페이로드에서 리소스의 구체적인 처리 수행     | 4.3.3    |
| PUT             | 대상 리소스의 모든 현재 표현을 요청 페이로드로  대체   | 4.3.4    |
| DELETE       | 대상 리소스의 현재 표현을 모두 제거                      | 4.3.5     |
| CONNECT   | 대상 리소스로 식별된 서버에 대한 터널 설립           | 4.3.6     |
| OPTIONS     | 대상 리소스에 대한 통신 옵션 설명                         | 4.3.7     |
| TRACE         | 대상 리소스의 경로를 따라 메시지 루프백 테스트를 수행             | 4.3.8     |

**Comment by humblEgo** [comment]
https://beecanvas.com/s/0Qa2r7nK3f6jU-rhvsLbB3k3T7ACRIbJnhlRu3h3pkWBSiuJYgIPgAIkoVJzDVyo

response 생성 흐름도 초안을 작성했습니다. 
이 수준에서 RFC 분석 & 세부구현을 진행할 예정이고 추후 추가로 파악한 사항을 반영하겠습니다.

**Comment by l-yohai** [comment]
명세서 수정된 거 넘 감동입니다..! 인준님상혁님 고생많으셨어요

**Comment by humblEgo** [comment]
https://docs.google.com/spreadsheets/d/1GNUoCfloWzp0r27ZsayIxHRwFWTl2l4ZfWlXcVARf98/edit#gid=1684315155

yohai님과 메소드/상태코드별 응답헤더 정리했습니다.
