### ISSUE TITLE
webserv 메인로직 뼈대구현

### ISSUE THREAD

**Issue by humblEgo** [get-Pork-Belly/Webserv#8]
설정파일 파싱 이후부터 메서드별 응답생성 직전까지의 메인로직 뼈대구현

**Comment by humblEgo** [comment]
Q) listen 함수의 두번째 인자인 backlog에 어떤 값을 넣어야하는가!
A) 15이상의 값.

에 대해서 찾아보니 보통 5를 넣어서 쓰지만, http 서버처럼 연결이 잦은 경우엔 15이상을 넣는다고 합니다. [링크](https://euney.tistory.com/entry/backlog%EB%9E%80)

우선 15로 하시죠!

**Comment by l-yohai** [comment]
좋습니다!

**Comment by humblEgo** [comment]
Q) select 함수의 timeout은 어떤 값이 적정한가!
A) 임의의 값을 줘도 무방하다고 여겨진다. 다만, 테스터를 통과하는지를 기준으로 삼자.

**Comment by l-yohai** [comment]
Q) Accept 함수에서 오류가 나타났을 때 어떻게 처리를 해야 하나?
A) [답변](https://kldp.org/node/122927) - OS 문제일 가능성이 높다. 예외 메세지만 던져 주는 것이 최선인 듯

**Comment by humblEgo** [comment]
> Q) Accept 함수에서 오류가 나타났을 때 어떻게 처리를 해야 하나?
> A) [답변](https://kldp.org/node/122927) - OS 문제일 가능성이 높다. 예외 메세지만 던져 주는 것이 최선인 듯

필요하다면, 일정시간 기다렸다가 다시 accept 시도해보고, 안되면 fd순회를 계속 시키는 식으로 구현하는식으로 구현할 수 도 있겠네요!

**Comment by l-yohai** [comment]
Non blocking에 대한 좋은 글이 있어서 공유드립니다. https://kldp.org/node/89385

**Comment by humblEgo** [comment]
> Non blocking에 대한 좋은 글이 있어서 공유드립니다. https://kldp.org/node/89385

지금 당장 파악이 어렵네요. 일단 구현하면서 시행착오를 겪어봐야할 것 같습니다. 다른 레포를 참고해보면 CGI를 쓸 때 특히 주의해야할 것 같아요~
